# LAB | Feature Engineering

**Load the data**

In this challenge, we will be working with the same Spaceship Titanic data, like the previous Lab. The data can be found here:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv

Metadata

https://github.com/data-bootcamp-v4/data/blob/main/spaceship_titanic.md

In [1]:
#Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [2]:
spaceship = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
spaceship.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

**Check the shape of your data**

In [3]:
display(spaceship.describe())
print(spaceship.shape)

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8514.000000,8512.000000,8510.000000,8485.000000,8510.000000,8505.000000
mean,28.827930,224.687617,458.077203,173.729169,311.138778,304.854791
std,14.489021,666.717663,1611.489240,604.696458,1136.705535,1145.717189
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,47.000000,76.000000,27.000000,59.000000,46.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

(8693, 14)

**Check for data types**

In [4]:
print(spaceship.dtypes)

PassengerId      object
HomePlanet       object
CryoSleep        object
Cabin            object
Destination      object
Age             float64
VIP              object
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Name             object
Transported        bool
dtype: object

**Check for missing values**

In [5]:
display(spaceship.isna().sum())

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

There are multiple strategies to handle missing data

- Removing all rows or all columns containing missing data.
- Filling all missing values with a value (mean in continouos or mode in categorical for example).
- Filling all missing values with an algorithm.

For this exercise, because we have such low amount of null values, we will drop rows containing any missing value.

In [6]:
spaceship_clean = spaceship.dropna()
spaceship_clean.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

- **Cabin** is too granular - transform it in order to obtain {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'T'}

In [7]:
spaceship_clean["Cabin"] = spaceship_clean["Cabin"].str.split("/").str[0]
spaceship_clean["Cabin"].head()

C:\Users\Ready2Use\AppData\Local\Temp\ipykernel_29772\1337691732.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  spaceship_clean["Cabin"] = spaceship_clean["Cabin"].str.split("/").str[0]

0    B
1    F
2    A
3    A
4    F
Name: Cabin, dtype: object

- Drop PassengerId and Name

In [8]:
spaceship_clean = spaceship_clean.drop(["PassengerId", "Name"], axis= 1)
spaceship_clean.head(30)

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,False,B,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,Earth,False,F,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,Europa,False,A,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,Europa,False,A,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,Earth,False,F,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True
5,Earth,False,F,PSO J318.5-22,44.0,False,0.0,483.0,0.0,291.0,0.0,True
6,Earth,False,F,TRAPPIST-1e,26.0,False,42.0,1539.0,3.0,0.0,0.0,True
8,Earth,False,F,TRAPPIST-1e,35.0,False,0.0,785.0,17.0,216.0,0.0,True
9,Europa,True,B,55 Cancri e,14.0,False,0.0,0.0,0.0,0.0,0.0,True
11,Europa,False,B,55 Cancri e,45.0,False,39.0,7295.0,589.0,110.0,124.0,True
12,Mars,False,F,TRAPPIST-1e,32.0,False,73.0,0.0,1123.0,0.0,113.0,True
13,Earth,False,G,TRAPPIST-1e,48.0,False,719.0,1.0,65.0,0.0,24.0,False
14,Earth,False,F,TRAPPIST-1e,28.0,False,8.0,974.0,12.0,2.0,7.0,True
17,Earth,False,F,55 Cancri e,24.0,False,0.0,1.0,0.0,0.0,637.0,False
18,Mars,True,F,TRAPPIST-1e,45.0,False,0.0,0.0,0.0,0.0,0.0,True
19,Earth,False,G,TRAPPIST-1e,0.0,False,0.0,0.0,0.0,0.0,0.0,True
20,Earth,False,F,55 Cancri e,14.0,False,412.0,0.0,1.0,0.0,679.0,False
21,Earth,True,E,TRAPPIST-1e,1.0,False,0.0,0.0,0.0,0.0,0.0,False
22,Earth,True,E,55 Cancri e,49.0,False,0.0,0.0,0.0,0.0,0.0,False
24,Earth,False,E,TRAPPIST-1e,10.0,False,0.0,0.0,0.0,0.0,0.0,True
26,Earth,False,E,TRAPPIST-1e,7.0,False,0.0,0.0,0.0,0.0,0.0,False
29,Earth,False,F,TRAPPIST-1e,15.0,False,0.0,225.0,0.0,998.0,0.0,False
30,Europa,False,C,55 Cancri e,34.0,False,22.0,6073.0,0.0,1438.0,328.0,False
31,Mars,False,F,TRAPPIST-1e,43.0,False,1125.0,0.0,136.0,48.0,0.0,False
32,Earth,False,G,TRAPPIST-1e,32.0,False,0.0,850.0,81.0,437.0,453.0,False
33,Mars,False,F,TRAPPIST-1e,47.0,False,214.0,0.0,1411.0,0.0,1229.0,True
34,Mars,False,F,TRAPPIST-1e,2.0,False,0.0,0.0,0.0,0.0,0.0,True
36,Europa,True,D,55 Cancri e,28.0,False,0.0,0.0,0.0,0.0,0.0,True
37,Mars,False,D,55 Cancri e,23.0,False,784.0,964.0,0.0,951.0,0.0,False
39,Earth,False,F,55 Cancri e,20.0,False,554.0,195.0,0.0,2606.0,0.0,False

- For non-numerical columns, do dummies.

In [9]:
# Separate features and target
y = spaceship_clean['Transported']
X = spaceship_clean.drop(columns=['Transported'])

# Select categorical columns
cat_cols = ['HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'VIP']

# Create encoder
ohe = OneHotEncoder(sparse_output=False, drop='first')

# Fit and transform ONLY categorical columns
X_train = ohe.fit_transform(X[cat_cols])

X_train

array([[1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 1.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 1., 0.]], shape=(6606, 13))

**Perform Train Test Split**

In [17]:
# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Encode
X_train_encoded = pd.DataFrame(
    ohe.fit_transform(X_train[cat_cols]),
    columns=ohe.get_feature_names_out(cat_cols),
    index=X_train.index
)

X_test_encoded = pd.DataFrame(
    ohe.transform(X_test[cat_cols]),
    columns=ohe.get_feature_names_out(cat_cols),
    index=X_test.index
)

# Combine
X_train_final = pd.concat([X_train.drop(columns=cat_cols), X_train_encoded], axis=1)
X_test_final = pd.concat([X_test.drop(columns=cat_cols), X_test_encoded], axis=1)

**Model Selection**

In this exercise we will be using **KNN** as our predictive model.

In [19]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_final, y_train)

KNeighborsClassifier()

In [20]:
y_pred = knn.predict(X_test_final)

In [21]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7700453857791225

In [22]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.77      0.78      0.77       661
        True       0.78      0.76      0.77       661

    accuracy                           0.77      1322
   macro avg       0.77      0.77      0.77      1322
weighted avg       0.77      0.77      0.77      1322

In [23]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.77      0.78      0.77       661
        True       0.78      0.76      0.77       661

    accuracy                           0.77      1322
   macro avg       0.77      0.77      0.77      1322
weighted avg       0.77      0.77      0.77      1322

- Evaluate your model's performance. Comment it

The KNN model achieved an accuracy of 77%, which indicates that it correctly predicts the outcome for most passengers.
But that the changes only marginally improved with todays adjustments.

The classification report shows that precision and recall are reasonably balanced, suggesting the model is not heavily biased toward one class.

However, KNN may not be the best model for this dataset because:

It is sensitive to feature scaling (if not normalized)
It can struggle with high-dimensional data (many dummy variables)

Overall, the model provides a baseline performance, but could likely be improved using more advanced models or tuning.